### ISSUE TITLE
Include of CodalDMESG should be CodalDmesg.h

### ISSUE THREAD

**Issue by dpgeorge** [lancaster-university/codal-nrf52#18]
In 0f801b97eef81d226ad1333a267f8d0be5db7687 some code was added which includes `CodalDMESG.h`, but I think this should be `CodalDmesg.h`.

**Comment by finneyj** [comment]
Thanks for flagging Damien - the pain of developing on windows! Will grep for it and factor these case typos out...

**Comment by finneyj** [comment]
Fixed in master.

**Comment by dpgeorge** [comment]
Thanks!  Can confirm it's now fixed.

**Comment by finneyj** [comment]
Great - thanks for confirming @dpgeorge
