### ISSUE TITLE
NRF52Pin fails to override setAnalogPeriodUs due to parameter type difference

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [lancaster-university/codal-nrf52#19]
NRF52Pin fails to override Pin::setAnalogPeriodUs due to parameter type difference (int vs unint32_t).

The value is ultimately passed to `pwm->setPeriodUs(int)` so perhaps it needs a size check too?

**Comment by finneyj** [comment]
Thanks @microbit-matt-hillsdon. Fixed in https://github.com/lancaster-university/codal-nrf52/commit/e9d44ac45b177a6c6d3fe48b2bdc9f219fcb41fb

**Comment by microbit-carlos** [comment]
Closing this as fixed, thanks Joe!
